### ISSUE TITLE
Error with `read_refs()` when trying to parse an APA PsycNet RIS file

### ISSUE THREAD

**Issue by danielvartan** [mjwestgate/synthesisr#13]
I encountered an error while trying to parse an exported RIS file from [APA PsycNet](https://psycnet.apa.org/) using `read_refs()`.

```{r}
Error in end_rows[1:(length(end_rows) - 1)] : 
  error only 0's can be mixed with negative subscriptions
```
> Tip: don't use `1:(length(end_rows) - 1)` is a bad practice. Use, for example, `seq_len(length(end_rows) - 1)` instead.

This error occurs with the function `synthesisr:::prep_ris()` . The function incorrectly put the `ER` (`end_row`) in the wrong column of the `z_dframe`  object. If you debug this function and set the correct index for the [`end_row` ](https://github.com/rmetaverse/synthesisr/blob/master/R/prep_ris.R#L92) all goes well.

I don't have the time to dig deeper into this problem right now. I will try to do this later.

**Comment by danielvartan** [comment]
Here is an example of an exported RIS file from [APA PsycNet](https://psycnet.apa.org/) (exported today).

https://drive.google.com/file/d/17rlvi5Y9enM1yOrRPiyfR6ulF5dO7jlv/view?usp=sharing

```{r}
file <- "C:\\Users\\Daniel\\Desktop\\PsycNET_Export.ris"
test <- synthesisr::read_ref(file)
Error in end_rows[1:(length(end_rows) - 1)] : 
  error only 0's can be mixed with negative subscriptions
```

**Comment by mjwestgate** [comment]
Thanks for letting me know - both issues appear to be fixed by [this commit](https://github.com/mjwestgate/synthesisr/commit/c406bc9f92c56dbcfb52700a8e0c81ab36cd2c01) - hopefully that should work for you now.
