### ISSUE TITLE
read_refs appears to duplicate records when reading in

### ISSUE THREAD

**Issue by befriendabacterium** [mjwestgate/synthesisr#16]
Hi Martin,

Having some odd behaviour reading in a bibliography file (.txt exported with ris-format from EndNote) with synthesisr:read_refs compared to revtools:read_bibliography. The file I am reading in has 729 records and reads fine with revtools:read_bibliography but synthesisr:read_refs adds a duplicate record, making it 730. See R code + outputs below:

`
> EnvironmentComplete_revtools<-revtools::read_bibliography('3_searching/4_search_outputs/main_searches/raw/EnvironmentComplete_300920.txt')
> nrow(EnvironmentComplete_revtools)
[1] 729
> EnvironmentComplete_synthesisr<-synthesisr::read_refs('3_searching/4_search_outputs/main_searches/raw/EnvironmentComplete_300920.txt')
> nrow(EnvironmentComplete_synthesisr)
[1] 730

`
In this example, synthesisr:read_refs is adding 1 record, but for other bib files it can be more. I attach the file to see if you can figure it out! Good luck, so long and thanks for all the packages!

Cheers
Matt

[EnvironmentComplete_300920.txt](https://github.com/rmetaverse/synthesisr/files/6465464/EnvironmentComplete_300920.txt)

**Comment by mjwestgate** [comment]
Hi Matt! 

With apologies for the delay, I think I've found the error here. Any time a line in a .ris file started with `ER` it was getting treated as an end row, hence adding breaks where none existed. This happens in your file on line number 12,084. I've fixed the issue in [this commit](https://github.com/mjwestgate/synthesisr/commit/c406bc9f92c56dbcfb52700a8e0c81ab36cd2c01).

One thing to consider is that this fix is is in the `prep_ris()` code, so if you're having problems with bibtex formatted documents then I'll need to keep looking - drop me a line if that's the case.

Martin

**Comment by befriendabacterium** [comment]
Nice! Damn you erthyhromycin, damn you to hell.

I moved away from working with bib now but I'm sure someone else will spot it or have spotted it already if they do have an issue.

Thanks!
Matt

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by mjwestgate** [comment]
Great - I’ll close this for now - but feel free to reopen if needed
