### ISSUE TITLE
detect_database() function: expected_columns not found

### ISSUE THREAD

**Issue by nscoble** [mjwestgate/synthesisr#5]
When running synthesisr (via litsearchr), importing files results in the error:

`Error in all.equal(colnames(df), expected_columns) : object 'expected_columns' not found`

I think this might be because of the [recent changes](https://github.com/rmetaverse/synthesisr/commit/38060a42be5fbe26f7733c0846d488f72f7ba490) to recognize preformatted files.

On line 144 of import_functions.R:
`all.equal(colnames(df), expected_columns)`

I think because `expected_columns` isn't defined anywhere there, it is throwing an error.

I am an R noob so I'm not sure what is going on, but when I am exploring the package Environment (in RStudio), I can see the `expected_columns` variable does have all the values listed in it. I'm just not sure why the function can't access that when it runs.

Thanks again for your amazing packages!

**Comment by mjwestgate** [comment]
Just checking old issues and found this one - sorry to return to this 18 months late! I think this question is obsolete now as `expected_columns` doesn't occur anywhere in the synthesisr repo. I'll close this as a result, but can reopen if it's still an issue.
